### ISSUE TITLE
app.py file -- a typo in the style className

### ISSUE THREAD

**Issue by topaccina** [Coding-with-Adam/response-reporting-dashboard#15]
hello @Coding-with-Adam,

there is a typo in line 79 of the app.py 
this is in the className.
current line is:
className="bg-opacity-10 p-2 bg-primary text-dark fw-bold rounded border border-light **vh-100**", 

but it should be

className="bg-opacity-10 p-2 bg-primary text-dark fw-bold rounded border border-light **mh-100**",

this is not visible in the homepage given the content is small but in case of page with larger content we need to exend the main container to the max page height.

Can you take note and fix in the next update? it is so small change that I am not sure it is needed a pull request for that.. In case let me know

**Comment by Coding-with-Adam** [comment]
Done. Thank you @topaccina

**Comment by topaccina** [comment]
thanks @Coding-with-Adam .
I did some other tests and also vh-100 could be an alternative option. Depends on style preferences: mh-100 adapt to the content , vh-100 fixed full heigth. 
Let's see when we put together all the parts what is the best
