### ISSUE TITLE
Requirements.txt empty in Nyv's Branch 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [Coding-with-Adam/response-reporting-dashboard#18]
Requirements.txt on @supernyv's empty.

**Comment by supernyv** [comment]
Hi Jorge,
I suspect these issues are due to not running the latest version. I suggest a "git pull" to update your local branch

**Comment by Coding-with-Adam** [comment]
I can confirm that @supernyv 's branch has a full [requirements.txt](https://github.com/Coding-with-Adam/response-reporting-dashboard/blob/nyv_branch/requirements.txt) file.
