### ISSUE TITLE
Date Picker Issue

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [Coding-with-Adam/response-reporting-dashboard#21]
# What happens

When the user files a report the only date that we can pick is the current date

# Expected behaviour 

Users should be able to pick any date in the past, since there is a lot of previous information that can be added to the database

**Comment by supernyv** [comment]
Hi Jorge,
This has now been updated. The limit is kept between 1970, and now, to ensure both that no impossible date in the past is selected and no date in the future is selected.

Does that mean the date a report is made on Watchtower does not have to be older than the response date from the platform?
For example:
![image](https://github.com/user-attachments/assets/99757aff-86b4-4bd8-849c-917f7b2b74dc)

**Comment by supernyv** [comment]
Issue closed, users can now pick any date in the past.
