### ISSUE TITLE
Dummy Data version with open cases

### ISSUE THREAD

**Issue by topaccina** [Coding-with-Adam/response-reporting-dashboard#5]
Hello,
I noticed that the dummy data files includes all closed cases. They all have Answer data.
I think that to improve the case tracking we should take into account also "still open" ones.
Started from the provided dataset I converted randomly  around 30% of the observations into open by set the cols ['Answer Date', 'Platform Decision', 'Policy', 'Appeal'] into Nan. I attached here the resulting csv. Let me know for any issue, ideas! 
[dummy_data_100_wNan.csv](https://github.com/Coding-with-Adam/response-reporting-dashboard/files/14896208/dummy_data_100_wNan.csv)
[dummy_data_1000_wNan.csv](https://github.com/Coding-with-Adam/response-reporting-dashboard/files/14896209/dummy_data_1000_wNan.csv)
[dummy_data_10000_wNan.csv](https://github.com/Coding-with-Adam/response-reporting-dashboard/files/14896210/dummy_data_10000_wNan.csv)

**Comment by JorgeMiguelGomes** [comment]
Good catch, and you're right!
Thank you for spotting that and creating this.
@Coding-with-Adam these should be the example datasets.
We are still missing the "screenshot" column, where the user will upload the contents' screenshot

**Comment by Coding-with-Adam** [comment]
Thank you @topaccina . I removed the complete csv sheets and replaced them with the ones you created in this issue.
